### ISSUE TITLE
#INC-5312: Missing image

### ISSUE THREAD

**Issue by vanessa-cooper** [ObelusFamily/Anythink-Market-uae7q#2]
Cool! Now, It seems that when creating a new product without an image, there are broken images showing up in the product catalog. Please fix this by replicating this bug locally with mock data.
Take a screenshot of the fix and attach it to a PR when you close the bug. There's a placeholder image in the repo that you can use named `placeholder.png`

**Comment by onlyhouse1980** [comment]
Just added placeholder to the editor file in the frontend. Seems to have done the trick
![editor](https://user-images.githubusercontent.com/56930138/180616027-f5150b19-c620-404c-b7fd-a7c489d7b139.png)
